CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, name TEXT NOT NULL, password_hash TEXT,
  role TEXT NOT NULL DEFAULT 'writer', avatar_url TEXT, bio TEXT, email_verified_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT UNIQUE NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS categories (id TEXT PRIMARY KEY, name TEXT UNIQUE NOT NULL, slug TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS tags (id TEXT PRIMARY KEY, name TEXT UNIQUE NOT NULL, slug TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS stories (
  id TEXT PRIMARY KEY, author_id TEXT NOT NULL REFERENCES users(id), category_id TEXT REFERENCES categories(id),
  title TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, excerpt TEXT, content TEXT NOT NULL, cover_url TEXT,
  status TEXT NOT NULL DEFAULT 'draft', featured INTEGER NOT NULL DEFAULT 0, published_at TEXT, scheduled_at TEXT,
  seo_title TEXT, seo_description TEXT, view_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS story_tags (story_id TEXT REFERENCES stories(id) ON DELETE CASCADE, tag_id TEXT REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY (story_id, tag_id));
CREATE TABLE IF NOT EXISTS comments (
  id TEXT PRIMARY KEY, story_id TEXT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  author_id TEXT NOT NULL REFERENCES users(id), parent_id TEXT REFERENCES comments(id) ON DELETE CASCADE,
  body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'visible', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS likes (user_id TEXT REFERENCES users(id) ON DELETE CASCADE, story_id TEXT REFERENCES stories(id) ON DELETE CASCADE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (user_id, story_id));
CREATE TABLE IF NOT EXISTS bookmarks (user_id TEXT REFERENCES users(id) ON DELETE CASCADE, story_id TEXT REFERENCES stories(id) ON DELETE CASCADE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (user_id, story_id));
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, type TEXT NOT NULL, payload TEXT NOT NULL DEFAULT '{}', read_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_stories_status_published ON stories(status, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_stories_author ON stories(author_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_story ON comments(story_id, created_at DESC);
